sonar.projectKey=fittrack-backend
sonar.projectName=FitTrack Backend
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,src/config/**,logs/**,**/logs/**
sonar.host.url=http://localhost:9000
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/app.js,src/server.js,src/config/**,src/models/**,src/routes/**,src/scripts/**,src/utils/**,src/middlewares/error.middleware.js,src/middlewares/validator.middleware.js
